<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Oidc\Controllers;

use Icinga\Exception\Http\HttpException;
use Icinga\Exception\NotFoundError;
use Icinga\Module\Oidc\ProviderRestrictor;
use Icinga\Module\Oidc\Controller;
use Icinga\Module\Oidc\Forms\ProviderForm;
use Icinga\Module\Oidc\Model\Provider;
use Icinga\Web\Notification;
use ipl\Html\Form;
use Icinga\Module\Oidc\Common\Database;
use ipl\Stdlib\Filter;
use ipl\Web\Url;


class ProviderController extends Controller
{
    /** @var Provider The Provider object */
    protected $provider;
    protected $db;

    public function init()
    {
        if(!$this->Auth()->hasPermission("oidc/provider/modify")){
            throw new HttpException(401,"Not allowed!");
        }
        $this->db=Database::get();

    }

    public function newAction()
    {

        $this->setTitle($this->translate('New Provider'));

        $values = [];

        $form = (ProviderForm::fromId(null))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(ProviderForm::ON_SUCCESS, function (ProviderForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Provider successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/providers')
                    );
                } else {
                    Notification::success($this->translate('Updated Provider successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/providers')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    public function editAction()
    {

        $this->setTitle($this->translate('Edit Provider'));

        $id = $this->params->getRequired('id');

        $query = Provider::on($this->db)->with([

        ]);
        $query->filter(Filter::equal('id', $id));

        $restrictor = new ProviderRestrictor();
        $restrictor->applyRestrictions($query);

        $provider = $query->first();
        if ($provider === null) {
            throw new NotFoundError(t('Entry not found'));
        }

        $this->provider = $provider;




        $values = $this->provider->getValues();




        $form = (ProviderForm::fromId($id))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(ProviderForm::ON_SUCCESS, function (ProviderForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Provider successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/providers')
                    );
                } else {
                    Notification::success($this->translate('Updated Provider successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/providers')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    protected function redirectForm(Form $form, $url)
    {
        if (
            $form->hasBeenSubmitted()
            && ((isset($form->valid) && $form->valid === true)
                || $form->isValid())
        ) {
            $this->redirectNow($url);
        }
    }
}
