<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Oidc\Controllers;

use Icinga\Exception\Http\HttpException;
use Icinga\Exception\NotFoundError;
use Icinga\Module\Oidc\UserRestrictor;
use Icinga\Module\Oidc\Controller;
use Icinga\Module\Oidc\Forms\UserForm;
use Icinga\Module\Oidc\Model\User;
use Icinga\Web\Notification;
use ipl\Html\Form;
use Icinga\Module\Oidc\Common\Database;
use ipl\Stdlib\Filter;
use ipl\Web\Url;


class UserController extends Controller
{
    /** @var User The User object */
    protected $user;
    protected $db;

    public function init()
    {
        if(!$this->Auth()->hasPermission("oidc/user/modify")){
            throw new HttpException(401,"Not allowed!");
        }
        $this->db=Database::get();

    }

    public function newAction()
    {

        $this->setTitle($this->translate('New User'));

        $values = [];

        $form = (UserForm::fromId(null))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(UserForm::ON_SUCCESS, function (UserForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed User successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                } else {
                    Notification::success($this->translate('Updated User successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    public function editAction()
    {

        $this->setTitle($this->translate('Edit User'));

        $id = $this->params->getRequired('id');

        $query = User::on($this->db)->with([

        ]);
        $query->filter(Filter::equal('id', $id));

        $restrictor = new UserRestrictor();
        $restrictor->applyRestrictions($query);

        $user = $query->first();
        if ($user === null) {
            throw new NotFoundError(t('Entry not found'));
        }

        $this->user = $user;




        $values = $this->user->getValues();




        $form = (UserForm::fromId($id))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(UserForm::ON_SUCCESS, function (UserForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed User successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                } else {
                    Notification::success($this->translate('Updated User successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    protected function redirectForm(Form $form, $url)
    {
        if (
            $form->hasBeenSubmitted()
            && ((isset($form->valid) && $form->valid === true)
                || $form->isValid())
        ) {
            $this->redirectNow($url);
        }
    }
}
