<?php

/* Originally from Icinga Web 2 Reporting Module (c) Icinga GmbH | GPLv2+ */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Oidc\Forms;

use Icinga\Forms\ConfigForm;

class ModuleconfigForm extends ConfigForm
{

    public function init()
    {

        $this->setName('oidc_settings');
        $this->setSubmitLabel($this->translate('Save Changes'));
    }

    public function createElements(array $formData)
    {
        $this->addElement('checkbox', 'mail_sendnotification', [
            'label' => $this->translate('Send notification?'),
        ]);
        $this->addElement('text', 'icingaweb2_fqdn', [
            'label' => $this->translate('IcingaWeb2 FQDN'),
        ]);
        $this->addElement('text', 'icingaweb2_port', [
            'label' => $this->translate('IcingaWeb2 Port'),
        ]);
        $this->addElement('select', 'icingaweb2_scheme', [
            'label' => $this->translate('IcingaWeb2 Scheme'),
            'multiOptions'=>['http'=>'http', 'https'=>'https']
        ]);
        $this->addElement('text', 'mail_subject', [
            'label' => $this->translate('Mail Subject'),
        ]);
        $this->addElement('text', 'mail_to', [
            'label' => $this->translate('Mail Receiver'),
        ]);
        $this->addElement('text', 'mail_from', [
            'label' => $this->translate('Mail Sender'),
        ]);
        $this->addElement('textarea', 'mail_body', [
            'label' => $this->translate('Mail Body'),
            'rows'=>10,
            'value'=> "A new User used %%PROVIDER%% to login to instance %%FQDN%%\nUsername: %%USERNAME%%\nclick here for further settings:\n%%USERURL%%\n"
        ]);

    }


}