<?php

/* originally from Icinga Web 2 Reporting Module | (c) 2019 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Oidc\Forms;

use Icinga\Module\Oidc\Common\Database;
use Icinga\Module\Oidc\Model\Provider;
use ipl\Html\Contract\FormSubmitElement;
use ipl\Html\FormElement\ColorElement;
use ipl\Html\HtmlDocument;
use ipl\Sql\Connection;
use ipl\Stdlib\Filter;
use ipl\Web\Compat\CompatForm;

class ProviderForm extends CompatForm
{

    protected $id;
    /** @var Connection $db */
    protected $db;
    protected $renderCreateAndShowButton = false;
    protected $submitButtonLabel;


    /**
     * Set whether the create and show submit button should be rendered
     *
     * @param bool $renderCreateAndShowButton
     *
     * @return \Icinga\Module\Oidc\Forms\ProviderForm
     */
    public function setRenderCreateAndShowButton(bool $renderCreateAndShowButton): self
    {
        $this->renderCreateAndShowButton = $renderCreateAndShowButton;

        return $this;
    }

    /**
     * Create a new form instance with the given provider id
     *
     * @param $id
     *
     * @return \Icinga\Module\Oidc\Forms\ProviderForm
     */
    public static function fromId($id): self
    {
        $form = new static();
        $form->id = $id;

        return $form;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getDb() :Connection
    {
        return $this->db;
    }

    public function setDb($db)
    {
        $this->db = $db;
        return $this;
    }


    public function hasBeenSubmitted(): bool
    {
        return $this->hasBeenSent() && (
                $this->getPopulatedValue('submit')
                || $this->getPopulatedValue('create_show')
                || $this->getPopulatedValue('remove')
            );
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }
    /**
     * Get the label of the submit button
     *
     * @return string
     */
    public function getSubmitButtonLabel(): string
    {
        if ($this->submitButtonLabel !== null) {
            return $this->submitButtonLabel;
        }

        return $this->id === null ? $this->translate('Create Provider') : $this->translate('Update Provider');
    }
    protected function assemble()
    {

        $columns = (new Provider())->getColumnDefinitions();

        foreach ($columns as $column=>$options){
            if(is_array($options)){
                $fieldtype = $options['fieldtype']??"text";
                unset($options['fieldtype']);
                if($fieldtype =="color"){
                    $this->addElement(new ColorElement($column,$options));
                }else{
                    $this->addElement($fieldtype, $column, $options);
                }

            }else{
                $this->addElement('text', $column, [
                    'label' => $options
                ]);
            }
        }
        $this->addElement('submit', 'submit', [
            'label' => $this->getSubmitButtonLabel()
        ]);
        if ($this->id !== null) {
            /** @var FormSubmitElement $removeButton */
            $removeButton = $this->createElement('submit', 'remove', [
                'label'          => $this->translate('Remove Provider'),
                'class'          => 'btn-remove',
                'formnovalidate' => true
            ]);
            $this->registerElement($removeButton);

            /** @var HtmlDocument $wrapper */
            $wrapper = $this->getElement('submit')->getWrapper();
            $wrapper->prepend($removeButton);


        } elseif ($this->renderCreateAndShowButton) {
            $createAndShow = $this->createElement('submit', 'create_show', [
                'label' => $this->translate('Create and Show'),
            ]);
            $this->registerElement($createAndShow);

            /** @var HtmlDocument $wrapper */
            $wrapper = $this->getElement('submit')->getWrapper();
            $wrapper->prepend($createAndShow);
        }

    }

    public function onSuccess()
    {
        /** @var Connection db */

        $values = $this->getValues();
        $model = new Provider();

        if ($this->id === null) {
            $values['ctime']=(new \DateTime())->format("Uv");
            $model->setValues($values);
            $model->save();
        } else {
            $model = Provider::on(Database::get())->filter(Filter::equal('id', $this->id))->first();
            if ($this->getPopulatedValue('remove')) {
                $model->delete();
                return;
            }

            $model->setValues($values);
            $model->id=$this->id;
            $model->save();

        }

    }


}
